### ISSUE TITLE
Deployment with GitHub Pages

### ISSUE THREAD

**Issue by devMunyi** [devMunyi/Portfolio#15]
Sorry, I had already deployed the project with Github Pages prior to reaching the task that needs a pull request on it. Please see a live version of my app on the following link:
https://devmunyi.github.io/Portfolio/

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @devMunyi👋, 

Your project is complete!  There is nothing else to say other than... it's time to close it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by devMunyi** [comment]
Thanks
